### ISSUE TITLE
Implement embeddable version of labs

### ISSUE THREAD

**Issue by ebidel** [googlecodelabs/codelab-components#13]
Here's a proposal to add a few properties (they're false by default so users get all the goodies). The use case is to turn things off / allow users of the the components to custom the styling of the elements themselves.

- [x] - `no-theme`: does not load our custom css. This might be the most difficult one because adding dynamic styles need to go through Polymer's style shimmer.
- [x] - `no-arrows`: hides the arrows
- [x] - `hide-toolbar`: hides the top nav. This is the `<paper-toolbar hidden$="[[hide-toolbar]]">` 

This properties also need to be added to `properties`

**Comment by crhym3** [comment]
How would it look like?

**Comment by ebidel** [comment]
@alialiafshar wants to learn him some Polymer!

**Comment by ebidel** [comment]
Top comment contains the basic implementation :)

**Comment by crhym3** [comment]
Yeah, sorry, github lagged behind a bit. Also, @alialiafshar is a nice alias to @aliafshar :)
