### ISSUE TITLE
codelab previous step FAB not positioned correctly in narrow mode

### ISSUE THREAD

**Issue by baabel** [googlecodelabs/codelab-components#22]
Looks like the **footer** element needs to be a child of 'main' when in narrow mode.

I took at look at production google codelab components and it appears they implemented the drawer panel using iron-media-query and iron-selector and additional **div** wrappers.  Any plans to merge those changes into this project?

![image](https://cloud.githubusercontent.com/assets/5082591/13115174/bfd87fda-d564-11e5-87db-db33fe7d24b5.png)

Thanks.

**Comment by ebidel** [comment]
I think the github page just needs updating.

**Comment by ebidel** [comment]
Hmm, this style should be applying: https://github.com/googlecodelabs/codelab-components/blob/1d528043b1d886df665881224898ef69ffc4f7ba/codelab-style.html#L52-L54 but for some reason it's not.

**Comment by ebidel** [comment]
Can you do me a favor, and remove `strip-whitespace` [here](https://github.com/googlecodelabs/codelab-components/blob/master/codelab-style.html#L20) and see if that fixes it?

**Comment by baabel** [comment]
I removed the strip-whitespace and see the same behavior.

#drawer[narrow] #controls {
  width: 100%;
}

I believe that the above style is not applying because it is a descendent selector and the footer tag (with id=controls) is not a child of the drawer panel (id=drawer)

**Comment by ebidel** [comment]
Right you are!
