### ISSUE TITLE
Polyserve : Throwing error " Use of const in strict mode. -  commandLineArgs" 

### ISSUE THREAD

**Issue by itsPR** [googlecodelabs/codelab-components#27]
Running polyserve throwing follow error
`const commandLineArgs = require('command-line-args');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)`

**Refer the image for more info**
![cl](https://cloud.githubusercontent.com/assets/2093818/15453298/39ed48aa-202e-11e6-8f53-86c2b50f5e9d.PNG)

**Comment by itsPR** [comment]
It should be fixed in polyserve #51 commit, 
https://github.com/PolymerLabs/polyserve/pull/51
But no luck??
node v0.12.5

**Comment by x1ddos** [comment]
@itsPR I'm afraid we will not be fixing this here but we're working on a drop-in replacement using just Custom Elements spec, without Polymer or other frameworks/libs, in https://github.com/googlecodelabs/codelab-elements.

See https://github.com/googlecodelabs/codelab-components/issues/49 for more details.
