### ISSUE TITLE
Remove custom handling of up, down, PgUp and PgDown

### ISSUE THREAD

**Issue by ddrone** [googlecodelabs/codelab-components#28]
Right now up, down, PgUp and PgDown are bound to move to previous / next step, which is incredibly frustrating since it changes default keyboard behaviour, which is to scroll down actual contents of a step using a keyboard. More than that, it seems that there are currently no way at all to scroll contents of a step using a keyboard, which forces the user to use mouse for no good reason. Please consider removing these keybindings.

Noticed this on https://codelabs.developers.google.com/codelabs/ng2-dart/index.html, but I'm pretty sure this would apply to other codelabs as well, thus reporting the issue here.

**Comment by crhym3** [comment]
Fixed by #29

**Comment by crhym3** [comment]
I will need some time to propagate this to codelabs.dgc site, but it'll be there soon.

**Comment by crhym3** [comment]
Hey @ddrone, I updated the site. How does  https://codelabs.developers.google.com/codelabs/ng2-dart/ look now?

It seem one still has to click on the content to be able to scroll up and down, but it's a step forward.

**Comment by ddrone** [comment]
Now it works much better, thanks!
