### ISSUE TITLE
Can't create a new instance, opens a blank screen

### ISSUE THREAD

**Issue by felipepbarreiros** [googlecodelabs/codelab-components#34]
When I run on polyserver, I get a blank screen with a few 404s:

![screen shot 2016-09-06 at 16 15 19](https://cloud.githubusercontent.com/assets/301819/18287340/25c63116-744d-11e6-93f4-9f45a58094a0.png)

**Comment by ebidel** [comment]
Looks like the deps didn't come down. Did you `bower install`?

**Comment by felipepbarreiros** [comment]
Yes, inside webcomponentsjs folder..

=================

Felipe-3:webcomponentsjs felipebarreiros$ bower install

bower cached
https://github.com/Polymer/web-component-tester.git#4.3.5

bower validate      4.3.5 against
https://github.com/Polymer/web-component-tester.git#^4.0.1

bower not-cached    git://github.com/polymerelements/test-fixture.git#^1.0.0

bower resolve       git://github.com/polymerelements/test-fixture.git#^1.0.0

bower cached        https://github.com/chaijs/chai.git#3.5.0

bower validate      3.5.0 against https://github.com/chaijs/chai.git#^3.2.0

bower cached        https://github.com/lodash/lodash.git#3.10.1

bower validate      3.10.1 against https://github.com/lodash/lodash.git#
^3.7.0

bower cached
https://github.com/GoogleChrome/accessibility-developer-tools.git#2.10.0

bower validate      2.10.0 against
https://github.com/GoogleChrome/accessibility-developer-tools.git#^2.10.0

bower cached        https://github.com/domenic/sinon-chai.git#2.8.0

bower validate      2.8.0 against https://github.com/domenic/sinon-chai.git#
^2.7.0

bower cached        https://github.com/blittle/sinon.js.git#1.17.1

bower validate      1.17.1 against https://github.com/blittle/sinon.js.git#
^1.14.1

bower cached        https://github.com/mochajs/mocha.git#2.5.3

bower validate      2.5.3 against https://github.com/mochajs/mocha.git#
^2.3.0

bower cached        https://github.com/PolymerLabs/stacky.git#1.3.2

bower validate      1.3.2 against https://github.com/PolymerLabs/stacky.git#
^1.3.0

bower cached        https://github.com/caolan/async.git#1.5.2

bower validate      1.5.2 against https://github.com/caolan/async.git#^1.5.0

bower download
https://github.com/polymerelements/test-fixture/archive/v1.1.1.tar.gz

bower extract       test-fixture#^1.0.0 archive.tar.gz

bower resolved      git://github.com/polymerelements/test-fixture.git#1.1.1

bower install       web-component-tester#4.3.5

bower install       accessibility-developer-tools#2.10.0

bower install       sinon-chai#2.8.0

bower install       sinonjs#1.17.1

bower install       chai#3.5.0

bower install       stacky#1.3.2

bower install       lodash#3.10.1

bower install       test-fixture#1.1.1

bower install       async#1.5.2

bower install       mocha#2.5.3


web-component-tester#4.3.5 www/lib/web-component-tester

├── accessibility-developer-tools#2.10.0

├── async#1.5.2

├── chai#3.5.0

├── lodash#3.10.1

├── mocha#2.5.3

├── sinon-chai#2.8.0

├── sinonjs#1.17.1

├── stacky#1.3.2

└── test-fixture#1.1.1


accessibility-developer-tools#2.10.0 www/lib/accessibility-developer-tools


sinon-chai#2.8.0 www/lib/sinon-chai


sinonjs#1.17.1 www/lib/sinonjs


chai#3.5.0 www/lib/chai


stacky#1.3.2 www/lib/stacky


lodash#3.10.1 www/lib/lodash


test-fixture#1.1.1 www/lib/test-fixture


async#1.5.2 www/lib/async


mocha#2.5.3 www/lib/mocha

Felipe-3:webcomponentsjs felipebarreiros$ polyserve

Starting Polyserve...

    serving on port: 8080

    from root:
/Users/felipebarreiros/Desktop/codelabs/www/lib/webcomponentsjs



Files in this directory are available under the following URLs

    applications: http://localhost:8080

    reusable components: http://localhost:8080/components/webcomponentsjs/







Felipe Barreiros

**Comment by felipepbarreiros** [comment]
And inside `codelab-components` as well... does it change anything?

I see the `iron-component-page` folder inside `codelab-components/www/lib`

**Comment by felipepbarreiros** [comment]
PS: Am I doing it right? I'm trying to create one of these for my own:
https://codelabs.developers.google.com/

**Comment by felipepbarreiros** [comment]
You were right, it is now working :D
