### ISSUE TITLE
Wrong slide behavior

### ISSUE THREAD

**Issue by lakshminathan** [googlecodelabs/codelab-components#38]
Consider for eg. if we are in step 3. Click the "Next step" icon. Now when you try to go to any previous step from the left panel you can note that the page slides from right which should have slided-in from the left side.

**Comment by x1ddos** [comment]
@lakshminathan I'm afraid we will not be fixing this here but we're working on a complete drop-in replacement using just Custom Elements spec, without Polymer or other frameworks/libs, in https://github.com/googlecodelabs/codelab-elements. See https://github.com/googlecodelabs/codelab-components/issues/49 for more details.

I cross-linked this issue from https://github.com/googlecodelabs/codelab-elements/issues/19.
