### ISSUE TITLE
FEATURE REQUEST: Add "Date Updated" to course page (all code labs)

### ISSUE THREAD

**Issue by oneezy** [googlecodelabs/codelab-components#41]
It would be cool if you guys could add the `Date Updated` to the  main course page also, as opposed to just having it on the main code labs page. 

![image](https://cloud.githubusercontent.com/assets/7369575/26755750/133f07ac-485a-11e7-9f25-49adb517be43.png)

**Comment by nimitbhargava** [comment]
So I got little curious about this feature - and found that this feature is already at `google-codelab.html`

![image](https://user-images.githubusercontent.com/8358694/33702730-f34dce40-db4a-11e7-863b-93b6f8dc96b1.png)

**Comment by x1ddos** [comment]
Yes, exactly. If you don't see a date, it means the codelab hasn't been updated to the newer version in which the date is present.
