### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by sinedied** [googlecodelabs/codelab-components#43]
Would you consider publishing these components as an npm package? Bower is deprecated now, and it would simplify usage workflow for creating codelabs.

**Comment by nimitbhargava** [comment]
Do you mean this on `bower install` ?

![image](https://user-images.githubusercontent.com/8358694/33698680-1b03af34-db34-11e7-8380-a6bca97d29f9.png)

**Comment by x1ddos** [comment]
@sinedied I'm afraid we will not be fixing this but we're working on a complete drop-in replacement using just Custom Elements spec, without Polymer or other frameworks/libs, in https://github.com/googlecodelabs/codelab-elements. See https://github.com/googlecodelabs/codelab-components/issues/49 for more details.

I've linked this from https://github.com/googlecodelabs/codelab-elements/issues/6 to make sure it's on the list.

**Comment by sinedied** [comment]
@x1ddos Thanks, the new version seems interesting!
