### ISSUE TITLE
Starting demo shows blank page

### ISSUE THREAD

**Issue by om26er** [googlecodelabs/codelab-components#44]
I cloned the project and ran `polyserve` in terminal, it gave
```
om26er@chaotic:~/code/ubuntu/codelab-components$ polyserve 
compile cache set to 52428800
Files in this directory are available under the following URLs
    applications: http://127.0.0.1:8081
    reusable components: http://127.0.0.1:8081/components/codelab-components/
```
But when I actually open that url, it just shows a blank page. Am I not supposed to see a demo codelab ?

**Comment by x1ddos** [comment]
@om26er I'm afraid we will not be fixing this here but we're working on a complete drop-in replacement using just Custom Elements spec, without Polymer or other frameworks/libs, in https://github.com/googlecodelabs/codelab-elements.

See https://github.com/googlecodelabs/codelab-components/issues/49 for more details.
