### ISSUE TITLE
Codelab title appears on hover over images, links

### ISSUE THREAD

**Issue by arthurevans** [googlecodelabs/codelab-components#6]
Not sure what's causing this, but it seems to be happening on all of the codelabs pages.

First reported here:

https://github.com/googlecodelabs/polymer-first-elements/issues/9

**Comment by ebidel** [comment]
We're using the `title` attribute, which the browser provides a11y for. Not much we can do about that other than to use another property.

BTW, this only happens on first load of a codelab, when the content area doesn't have focus yet. After you click in the content are, it doesn't pop up anymore.
