### ISSUE TITLE
Cannot read property 'mq' of undefined

### ISSUE THREAD

**Issue by crhym3** [googlecodelabs/codelab-components#8]
Not sure how consistently this can be repro, but anyway:

1. Go to https://code-labs.io/android-dev-summit.
2. Open js console and make sure "Disable cache" is not checked on the Network tab.
3. Focus URL bar (cmd+L) and hit enter. This is different from refresh.
4. Observe splash screen and then blank page:

![screen shot 2015-11-18 at 6 38 25 pm](https://cloud.githubusercontent.com/assets/25405/11250460/72dc748e-8e24-11e5-874f-1302328a4a67.png)

Users wouldn't normally navigate this way but I noticed this is also happening during normal navigation, e.g. selecting a view from the drop-down from the main index. Not as consistent though, hence the steps above.

**Comment by ebidel** [comment]
There's an internal bug for this. It's a lazy loading race condition on the site. These elements are good to go.
